name: Vercel Auto Deploy

on:
  schedule:
    - cron: '0 */8 * * *'  # Execute every 8 hours
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_4c6XMs3WQ74YQ9CTrDnoQ0RDWm40/hQqEjlS1aL